version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: prepare
          command: |
            pacman -Syu --needed --noconfirm base-devel git ssh cmake catch2
      - checkout
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake \
              -DBUILD_TESTS=false \
              -DBUILD_SHARED_LIBS=true \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/usr \
              ..
            make
      - run:
          name: test
          command: |
            cd build
            cmake \
              -DBUILD_TESTS=true \
              -DBUILD_SHARED_LIBS=true \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/usr \
              ..
            make
            make test
      - run:
          name: generate-source-package
          command: |
            useradd -m builder
            cd libhello/package/archlinux
            ./configure.sh
      - run:
          name: make-package
          command: |
            pacman -S --noconfirm devtools
            cd libhello/package/archlinux/source-package
            sudo -u builder extra-x86_64-build
  build:
    docker:
      - image: alpine:edge
    steps:
      - run:
          name: install
          command: |
            apk upgrade
            apk add g++ cmake make git
            git clone https://github.com/catchorg/Catch2.git
            cd Catch2
            cmake -Bbuild -H. -DBUILD_TESTING=OFF
            cmake --build build/ --target install
            cd ..
            rm -rf Catch2
      - checkout
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake ..
            make
            make test
            mkdir pkg
            make DESTDIR=pkg install
  build2:
    docker:
      - image: ubuntu:disco
    steps:
      - run:
          name: install
          command: |
            apt update && apt -y upgrade
            apt -y install build-essential cmake git
            git clone https://github.com/catchorg/Catch2.git
            cd Catch2
            cmake -Bbuild -H. -DBUILD_TESTING=OFF
            cmake --build build/ --target install
            cd ..
            rm -rf Catch2
      - checkout
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake ..
            make
            make test
            mkdir pkg
            make DESTDIR=pkg install

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - build

